# Generated by Django 2.2.6 on 2019-11-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cableadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='password',
            field=models.CharField(default='123', max_length=20),
        ),
    ]
