# Generated by Django 2.2.6 on 2019-11-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cableadmin', '0002_manager_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='collector_id',
            field=models.CharField(default='21', max_length=5),
        ),
    ]
