# Generated by Django 2.2.6 on 2019-11-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cableadmin', '0003_customers_collector_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='password',
            field=models.CharField(default='abc', max_length=20),
        ),
    ]
