# Generated by Django 2.2.6 on 2019-11-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cableadmin', '0004_customers_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='subscription_for',
        ),
        migrations.AddField(
            model_name='customers',
            name='subscription_cable',
            field=models.CharField(default='1 MONTH', max_length=20),
        ),
        migrations.AddField(
            model_name='customers',
            name='subscription_wifi',
            field=models.CharField(default='1 MONTH', max_length=20),
        ),
    ]
